name: Keep API Alive
on:
  schedule:
    - cron: '*/6 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://mean-variance-app-5are.onrender.com/
